version: "3"
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: ["npm", "run", "dev"]
    links:
      - mongodb
    ports:
      - "3000:8000"
    volumes:
      - ./config:/home/node/config
      - ./etc:/home/node/etc
      - ./src:/home/node/src
      - ./test:/home/node/test

  mongodb:
    image: mongo:4.0.0
    ports:
      - "27017:27017"
    volumes:
      - ~/data/mongo:/data/db
