version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Build docker image
          command: |
            docker build -t another-rest-api .

      - run:
          name: Run unit test
          command: |
            mkdir -p coverage
            chmod 777 coverage
            docker-compose -f docker-compose.test.yml build
            docker-compose -f docker-compose.test.yml up 

